### ISSUE TITLE
Why using C and not Rust

### ISSUE THREAD

**Issue by danmx** [wasmerio/kernel-wasm#10]
Why did you decide to write this kernel modules in C instead of Rust? Is the ecosystem not mature enough to write kernel modules in Rust? Was it done in C because you plan to ship it upstream?

**Comment by losfair** [comment]
In kernel-wasm we use a lot of low-level kernel APIs (for memory management, userspace interfacing, etc.), most of which not being trivial to create a safe wrapper in Rust.

In the future if the Rust ecosystem for kernel modules becomes more mature, maybe the WASI/networking parts would be good first candidates to rewrite in Rust.
